RF: explicitly check for SYNC_FILE being present or symlink
Because it seems that ruyaml or whatnot overloaded FileNotFound exception
and thus it was bubbling up as

	----------------------------
	Traceback (most recent call last):
	  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 452, in sync_zarr
		await zsync.run()
	  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 126, in run
		last_sync = self.read_sync_file()
	  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 240, in read_sync_file
		data = SyncData.parse_file(self.repo / SYNC_FILE)
	  File "pydantic/main.py", line 556, in pydantic.main.BaseModel.parse_file
	  File "pydantic/parse.py", line 64, in pydantic.parse.load_file
	  File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
	  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/json/__init__.py", line 357, in loads
		return _default_decoder.decode(s)
	  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/json/decoder.py", line 337, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/json/decoder.py", line 355, in raw_decode
		raise JSONDecodeError("Expecting value", s, err.value) from None
	json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

on 000108.  I hope this would address the issue but have not tested yet